src/Entity/Rencontre.php
<?php

namespace App\Entity;

use App\ApiResource\ApiRencontre;
use \DateTime;

use App\Repository\RencontreRepository;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RencontreRepository::class)]
class Rencontre
{
    //Le match peut être « Termine », « À venir », « En Cours » 
    public const STATUT_A_VENIR = 0;
    public const STATUT_EN_COURS = 1;
    public const STATUT_TERMINE = 2;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $heureDebut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $heureFin = null;

    #[ORM\Column]
    private ?int $statut = null;

    #[ORM\Column]
    private ?int $scoreEquipeA = null;

    #[ORM\Column(nullable: true)]
    private ?int $scoreEquipeB = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meteo = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Equipe $equipeA = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Equipe $equipeB = null;

    #[ORM\Column]
    private ?float $coteEquipeA = null;

    #[ORM\Column]
    private ?float $coteEquipeB = null;

    #[ORM\OneToMany(mappedBy: 'rencontre', targetEntity: Commentaire::class, orphanRemoval: true, cascade: ['persist', 'remove'])]
    private Collection $commentaires;

    #[ORM\OneToMany(mappedBy: 'rencontre', targetEntity: Pari::class, orphanRemoval: false, cascade: ['persist', 'remove'])]
    private Collection $paris;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
        $this->paris = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Retourne le total des mises sur la rencontre
     * @return float
     */
    public function getTotalDesMises(): float
    {
        return $this->paris->map(function ($paris) {
                return $paris->getMise(); 
            })->reduce(function(float $accumulator, float $value): float {
                return $accumulator + $value;
            }, 0);
    }

    /**
     * Retourne le total des mises sur l'équipe A
     * @return float
     */
    public function getNombreDeParisSurEquipeA(): int
    {
        return $this->paris->map(function ($paris) {
                if ($paris->getEquipe() == $this->equipeA) {
                    return 1; 
                } else {
                    return 0;
                }
                return $paris->getMise(); 
            })->reduce(function(float $accumulator, float $value): float {
                return $accumulator + $value;
            }, 0);
    }

    /**
     * Retourne le total des mises sur l'équipe B
     * @return float
     */
    public function getNombreDeParisSurEquipeB(): int
    {
        return $this->paris->map(function ($paris) {
                if ($paris->getEquipe() == $this->equipeB) {
                    return 1; 
                } else {
                    return 0;
                }
                return $paris->getMise(); 
            })->reduce(function(float $accumulator, float $value): float {
                return $accumulator + $value;
            }, 0);
    }

    /**
     * Retourne un objet ApiRencontre à partir de l'entité
     *
     * @return ApiRencontre
     */
    public function toApiRencontre(): ApiRencontre {
        $rencontre = new ApiRencontre();
        $rencontre->id = $this->getId();
        $rencontre->heureDebut = $this->getHeureDebut();
        $rencontre->heureFin = $this->getHeureFin();
        $rencontre->statut = $this->getStatut();
        $rencontre->scoreEquipeA = $this->getScoreEquipeA();
        $rencontre->scoreEquipeB = $this->getScoreEquipeB();
        $rencontre->meteo = $this->getMeteo();
        $rencontre->equipeA = $this->getEquipeA()->getNom();
        $rencontre->equipeB = $this->getEquipeB()->getNom();
        $rencontre->coteEquipeA = $this->getCoteEquipeA();
        $rencontre->coteEquipeB = $this->getCoteEquipeB();
        $rencontre->totalDesMises = $this->getTotalDesMises();
        $rencontre->nombreDeParisSurEquipeA = $this->getNombreDeParisSurEquipeA();
        $rencontre->nombreDeParisSurEquipeB = $this->getNombreDeParisSurEquipeB();
        return $rencontre;
    }

    /**
     * Retourne les commentaires de la rencontre avec l'heure du commentaire
     * relative au début de la rencontre (en minutes depuis le début)
     * @return float
     */
    public function getTimedCommentaires(): ?array
    {
        return $this->commentaires->map(function ($commentaire) {
            $time = $this->heureDebut->diff($commentaire->getDateHeure())->i;
            return $time . 'm ' . $commentaire->getTexte(); 
        })->toArray();
    }

    /**
     * Retourne le jour de la rencontre à partir de l'heure de début
     * Formatté en français
     *
     * @return string|null
     */
    public function getJour(): ?string
    {
        $formatter = new \IntlDateFormatter('fr_FR', \IntlDateFormatter::LONG, \IntlDateFormatter::NONE);
        return $formatter->format($this->heureDebut);
    }

    /**
     * Retourne l'heure de début et de fin de la rencontre séparés par un tiret 
     * dans une chaîne de caractères
     * 
     * @return string|null
     */
    public function getHoraire(): ?string
    {
        return $this->heureDebut->format('H:i') . ' - ' . $this->heureFin->format('H:i');
    }

    public function getHeureDebut(): ?\DateTimeInterface
    {
        return $this->heureDebut;
    }

    public function setHeureDebut(\DateTimeInterface $heureDebut): static
    {
        $this->heureDebut = $heureDebut;

        return $this;
    }

    public function getHeureFin(): ?\DateTimeInterface
    {
        return $this->heureFin;
    }

    public function setHeureFin(\DateTimeInterface $heureFin): static
    {
        $this->heureFin = $heureFin;

        return $this;
    }

    public function getStatut(): ?int
    {
        return $this->statut;
    }

    public function getStatutString(): ?string
    {
        $statuses = [
            self::STATUT_A_VENIR => 'À venir',
            self::STATUT_EN_COURS => 'En cours',
            self::STATUT_TERMINE => 'Terminé'
        ];
        return $statuses[$this->statut];
    }

    public function isTerminee(): bool
    {
        return $this->statut == self::STATUT_TERMINE;
    }

    public function isAvenir(): bool
    {
        return $this->statut == self::STATUT_A_VENIR;
    }

    public function setStatut(int $statut): static
    {
        $this->statut = $statut;
        return $this;
    }

    public function getDisplayableScores(): ?string
    {
        if ($this->statut == self::STATUT_A_VENIR) {
            return '—';
        } else {
            return $this->scoreEquipeA . ' - ' . $this->scoreEquipeB;
        }
    }

    public function getScoreEquipeA(): ?int
    {
        return $this->scoreEquipeA;
    }

    public function setScoreEquipeA(int $scoreEquipeA): static
    {
        $this->scoreEquipeA = $scoreEquipeA;

        return $this;
    }

    public function getScoreEquipeB(): ?int
    {
        return $this->scoreEquipeB;
    }

    public function setScoreEquipeB(?int $scoreEquipeB): static
    {
        $this->scoreEquipeB = $scoreEquipeB;

        return $this;
    }

    public function getMeteo(): ?string
    {
        return $this->meteo;
    }

    public function setMeteo(?string $meteo): static
    {
        $this->meteo = $meteo;

        return $this;
    }

    public function getEquipeA(): ?Equipe
    {
        return $this->equipeA;
    }

    public function setEquipeA(Equipe $equipeA): static
    {
        $this->equipeA = $equipeA;

        return $this;
    }

    public function getEquipeB(): ?Equipe
    {
        return $this->equipeB;
    }

    public function setEquipeB(Equipe $equipeB): static
    {
        $this->equipeB = $equipeB;

        return $this;
    }

    public function getCoteEquipeA(): ?float
    {
        return $this->coteEquipeA;
    }

    public function setCoteEquipeA(float $coteEquipeA): static
    {
        $this->coteEquipeA = $coteEquipeA;

        return $this;
    }

    public function getCoteEquipeB(): ?float
    {
        return $this->coteEquipeB;
    }

    public function setCoteEquipeB(float $coteEquipeB): static
    {
        $this->coteEquipeB = $coteEquipeB;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): static
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setRencontre($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): static
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getRencontre() === $this) {
                $commentaire->setRencontre(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Pari>
     */
    public function getParis(): Collection
    {
        return $this->paris;
    }

    public function addPari(Pari $pari): static
    {
        if (!$this->paris->contains($pari)) {
            $this->paris->add($pari);
            $pari->setRencontre($this);
        }

        return $this;
    }
}

src/Controller/RencontreController.php
<?php

namespace App\Controller;

use App\Entity\Rencontre;
use App\Form\RencontreType;
use App\ApiResource\ApiRencontre;

use App\Repository\RencontreRepository;
use App\Service\GestionRencontre;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpKernel\Attribute\AsController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

#[AsController]
class RencontreController extends AbstractController
{
    public function __construct(
        private RencontreRepository $rencontreRepository,
        private EntityManagerInterface $entityManager
    ) {}

    /**
     * Liste les matches
     *
     * @param RencontreRepository $rencontreRepository
     * @return Response
     */
    #[Route('/rencontres', name: 'app_rencontre')]
    public function index(): Response
    {
        $rencontres = $this->rencontreRepository->toutesLesRencontres();
        return $this->render('rencontre/index.html.twig', [
            'rencontres' => $rencontres,
        ]);
    }

    /**
     * Détail d'un match
     */
    #[Route('/rencontres/{id}', name: 'app_show_rencontre')]
    public function show(int $id): Response
    {
        $rencontre = $this->rencontreRepository->findRencontreById($id);
        return $this->render('rencontre/show.html.twig', [
            'rencontre' => $rencontre,
        ]);
    }

    /**
     * Liste les matches, mais à des fins d'administration
     *
     * @param RencontreRepository $rencontreRepository
     * @return Response
     */
    #[Route('/admin/rencontres', name: 'app_admin_rencontres')]
    public function adminIndex(): Response
    {
        $rencontres = $this->rencontreRepository->toutesLesRencontres();
        return $this->render('rencontre/admin.index.html.twig', [
            'rencontres' => $rencontres,
        ]);
    }

    /**
     * Modifier un match
     */
    #[Route('/admin/rencontres/{id}', name: 'app_edit_rencontre')]
    public function edit(int $id, Request $request): Response
    {
        $rencontre = $this->rencontreRepository->findOneById($id);
        if (!$rencontre) {
            throw $this->createNotFoundException('Match non trouvé !');
        }
        $form = $this->createForm(RencontreType::class, $rencontre);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $rencontre = $form->getData();
            $this->entityManager->persist($rencontre);
            $this->entityManager->flush();
            $this->addFlash('success', "Le match a été modifié avec succès.");
            return $this->redirectToRoute('app_admin_rencontres');
        }

        return $this->render('rencontre/edit.html.twig', [
            'rencontre' => $rencontre,
            'form' => $form,
        ]);
    }

    /**
     * Créer un match
     */
    #[Route('/admin/rencontres/create', name: 'app_create_rencontre', priority: 1)]
    public function create(Request $request): Response
    {
        $rencontre = new Rencontre();
        $form = $this->createForm(RencontreType::class, $rencontre);

        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $rencontre = $form->getData();
                $this->entityManager->persist($rencontre);
                $this->entityManager->flush();
                $this->addFlash('success', "Le match a été créé avec succès.");
                return $this->redirectToRoute('app_admin_rencontres');
            } else  {
                $errors = $form->getErrors();
                dd($errors);
                $this->addFlash('error', "Le match n'a pas pu être créé.");
                foreach ($errors as $error) {
                    $this->addFlash('error', $error->getMessage());
                }
            }
        }

        return $this->render('rencontre/create.html.twig', [
            'form' => $form,
        ]);
    }

    /**
     * Supprimer un match
     */
    #[Route('/admin/rencontres/{id}/delete', name: 'app_delete_rencontre')]
    public function delete(int $id): Response
    {
        $rencontre = $this->rencontreRepository->findOneById($id);
        if (!$rencontre) {
            throw $this->createNotFoundException('Match non trouvé !');
        }

        //Il n'est pas possible de supprimer une rencontre si elle est commencée ou terminée
        $rencontre = $this->rencontreRepository->findOneById($id);
        if ($rencontre->getEtat() != Rencontre::ETAT_A_VENIR) {
            $this->addFlash('error', "Le match ne peut pas être supprimé car il est commencé ou terminé.");
            return $this->redirectToRoute('app_admin_rencontres');
        }

        //Il n'est pas possible de supprimer une rencontre si des paris ont été faits sur elle
        $pariRepository = $this->entityManager->getRepository(Pari::class);
        if ($pariRepository->countAllParisForEquipeId($id) > 0) {
            $this->addFlash('error', "Le match ne peut pas être supprimé car des paris ont été faits sur lui.");
            return $this->redirectToRoute('app_admin_rencontres');
        }
        
        $this->entityManager->remove($rencontre);
        $this->entityManager->flush();
        $this->addFlash('success', "Le match a été supprimé avec succès.");
        return $this->redirectToRoute('app_admin_rencontres');
    }

    /**
     * Action personnalisé de l'API
     * 
     * Clôture un match et calcule les gains des paris par Web Service
     * 
     * Un commentateur peut clore un match à l’issue de la rencontre, l’action est manuelle, 
     * car un match peut durer plus longtemps que le temps donné s’il y a eu prolongation. 
     * Si le temps a été dépassé, l’action de « clore » un match change l’heure de fin de celui-ci.
     * La fermeture d’un match calcule le montant gagné ou perdu par l’utilisateur en fonction de son pari.
     *
     * @param Rencontre $rencontre
     * @param GestionRencontre $gestionRencontre
     * @return Rencontre
     */
    public function __invoke(Rencontre $rencontre, GestionRencontre $gestionRencontre): ApiRencontre
    {
        $rencontre = $gestionRencontre->cloturer($rencontre);
        return $rencontre->toApiRencontre();
    }
}

templates/rencontre/admin.index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gérer les matchs{% endblock %}

{% block body %}

{% include 'menu.html.twig' %}

<div class="container-fluid">
    <div class="row"><div class="col-12">&nbsp;</div></div>
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10">
            <h2 id="titleMatches">Gérer les matchs <a class="btn btn-primary" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Cliquez pour ajouter un match" href="{{ path('app_create_rencontre') }}"><i class="bi bi-plus"></i></a></h2>
            {% if rencontres is empty %}
            <p id="msgNoMatchFound">Oups ! Une erreur est apparue</p>
            {% else %}

            <p>Cliquez sur une ligne pour modifier un match :</p>

            <div data-controller="tableManager">

                <div class="form-floating gx-2">
                    <input name="txtFilter" data-tableManager-target="source" data-action="input->tableManager#filter" type="text" class="form-control" />
                    <label for="txtFilter" class="form-label">Chercher un match :</label>
                </div>
                <br />

                <table class="table table-rounded">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Heure début - fin</th>
                            <th>Equipe A</th>
                            <th>Cotes équipes A - B</th>
                            <th>Equipe B</th>
                            <th>Statut</th>
                            <th>Météo</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for rencontre in rencontres %}
                        <tr class="clickable" data-action="click->tableManager#show" data-tableManager-url-param="{{ path('app_edit_rencontre', {id: rencontre.id}) }}"
                        data-tableManager-target="filterable" data-tableManager-key="{{ rencontre.EquipeA.Nom|e }} {{ rencontre.EquipeB.Nom|e }} {{ rencontre.statutString|e }} {{ rencontre.jour }}">
                            <td><i class="bi bi-caret-right-square-fill"></i>&nbsp;{{ rencontre.jour }}</td>
                            <td>{{ rencontre.horaire }}</td>
                            <td>{{ rencontre.EquipeA.Nom |e }}</td>
                            <td><span class="badge rounded-pill bg-info text-dark">{{ rencontre.CoteEquipeA |e}} &mdash; {{ rencontre.CoteEquipeB |e}}</span></td>
                            <td>{{ rencontre.EquipeB.Nom |e }}</td>
                            <td>{{ rencontre.statutString |e }}</td>
                            <td>{{ rencontre.meteo |e }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% endif %}
        </div>
        <div class="col-1"></div>
    </div>
</div>
{% endblock %}

templates/rencontre/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer une rencontre{% endblock %}

{% block body %}

{% include 'menu.html.twig' %}

        {% include 'alert.error.html.twig' %}

        <div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
            <div class="col-md-6">
                <h2 class="mb-4">Création d'une nouvelle rencontre</h2>

                {{ form_errors(form) }}

                {{ form_start(form) }}
                    <div class="mb-3">
                        <div class="form-floating gx-2">
                        {{ form_widget(form.equipeA) }}
                        <label for="rencontre_equipeA" class="form-label">Équipe A</label>
                        </div>
                    </div>
                    <div class="mb-3">
                        <div class="form-floating gx-2">
                        {{ form_widget(form.equipeB) }}
                        <label for="rencontre_equipeB" class="form-label">Équipe B</label>
                        </div>
                    </div>

                    <div class="mb-3">
                        <div class="form-floating gx-2">
                            <input name="{{ field_name(form.heureDebut) }}" type="datetime-local" class="form-control" required="required" />
                            <label for="heureDebut" class="form-label">Heure de début</label>
                        </div>
                    </div>
                    <div class="mb-3">
                        <div class="form-floating gx-2">
                            <input name="{{ field_name(form.heureFin) }}" type="datetime-local" class="form-control" required="required" />
                            <label for="heureFin" class="form-label">Heure de fin</label>
                        </div>
                    </div>

                    <div class="mb-3">
                        <div class="form-floating gx-2">
                            <input name="{{ field_name(form.coteEquipeA) }}" value="{{ field_value(form.coteEquipeA) }}" type="number" min="1" max="100" step="0.01" class="form-control" required="required" />
                            <label for="coteEquipeA" class="form-label">Cote équipe A</label>
                        </div>
                    </div>

                    <div class="mb-3">
                        <div class="form-floating gx-2">
                            <input name="{{ field_name(form.coteEquipeB) }}" value="{{ field_value(form.coteEquipeB) }}" type="number" min="1" max="100" step="0.01" class="form-control" required="required" />
                            <label for="coteEquipeB" class="form-label">Cote équipe B</label>
                        </div>
                    </div>

                    <div class="mb-3">
                        <div class="form-floating gx-2">
                            <input name="{{ field_name(form.meteo) }}" value="{{ field_value(form.meteo) }}" type="text" class="form-control" required="required" />
                            <label for="meteo" class="form-label">Météo</label>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary">Enregistrer</button>
                    <a href="{{ path('app_admin_rencontres') }}" class="btn btn-secondary">Annuler</a>
                {{ form_end(form) }}
                    
            </div>
        </div>
{% endblock %}

templates/rencontre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Visualiser tous les matchs{% endblock %}

{% block body %}

{% include 'menu.html.twig' %}

<div class="container-fluid">
    <div class="row"><div class="col-12">&nbsp;</div></div>
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10">
            <h2 id="titleMatches">Tous les matchs</h2>
            {% if rencontres is empty %}
            <p id="msgNoMatchFound">Oups ! Une erreur est apparue</p>
            {% else %}

            <p>Cliquez sur une ligne pour accèder aux détails d'un match :</p>

            <div data-controller="tableManager">

                <div class="form-floating gx-2">
                    <input name="txtFilter" data-tableManager-target="source" data-action="input->tableManager#filter" type="text" class="form-control" />
                    <label for="txtFilter" class="form-label">Chercher un match :</label>
                </div>
                <br />

                <table class="table table-rounded">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Heure début - fin</th>
                            <th>Equipe A</th>
                            <th>Cotes équipes A - B</th>
                            <th>Equipe B</th>
                            <th>Statut</th>
                            <th>Score</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for rencontre in rencontres %}
                        <tr class="clickable" data-action="click->tableManager#show" data-tableManager-url-param="{{ path('app_show_rencontre', {id: rencontre.id}) }}"
                        data-tableManager-target="filterable" data-tableManager-key="{{ rencontre.EquipeA.Nom|e }} {{ rencontre.EquipeB.Nom|e }} {{ rencontre.statutString|e }} {{ rencontre.jour }}">
                            <td><i class="bi bi-caret-right-square-fill"></i>&nbsp;{{ rencontre.jour }}</td>
                            <td>{{ rencontre.horaire }}</td>
                            <td>{{ rencontre.EquipeA.Nom |e }}</td>
                            <td><span class="badge rounded-pill bg-info text-dark">{{ rencontre.CoteEquipeA |e}} &mdash; {{ rencontre.CoteEquipeB |e}}</span></td>
                            <td>{{ rencontre.EquipeB.Nom |e }}</td>
                            <td>{{ rencontre.statutString |e }}</td>
                            <td>{{ rencontre.displayableScores |e }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% endif %}
        </div>
        <div class="col-1"></div>
    </div>
</div>
{% endblock %}

templates/rencontre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails du match{% endblock %}

{% block body %}

{% include 'menu.html.twig' %}

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
        <h1><small class="text-muted">Match</small> {{ rencontre.equipeA.Nom |e }} &nbsp;
        <span class="badge rounded-pill bg-info text-dark">{{ rencontre.coteEquipeA |e}} &mdash; {{ rencontre.coteEquipeB |e}}</span>
        &nbsp;{{ rencontre.equipeB.Nom |e }} </h1>

        <div class="card-body">
            Jour du match : {{ rencontre.jour }}<br />
            Horaire : {{ rencontre.heureDebut |date("H:i") }} - {{ rencontre.heureFin |date("H:i") }}<br />
            Cotes : {{ rencontre.coteEquipeA |e}} contre {{ rencontre.coteEquipeB |e}}<br />
            Statut : {{ rencontre.statutString |e }}<br />
            Météo : {{ rencontre.meteo |e }}<br />
            
            {% if rencontre.isavenir %}
            <a href="{{ path('app_pari_rencontre', {id: rencontre.id}) }}" class="btn btn-primary">Miser</a>
            {% else %}

            Score : {{ rencontre.displayableScores |e }}<br />
        </div>

        <h3>Commentaires</h3>
        {% if rencontre.equipeA.joueurs is empty %}
        <p id="msgNoComments">Aucun commentaire pour le momment.</p>
        {% else %}
        <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseCommentaires" aria-expanded="false" aria-controls="collapseExample">
        Voir les commentaires du match
        </button>
        <div class="collapse" id="collapseCommentaires">
            <table class="table">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Commentaire</th>
                    </tr>
                </thead>
                <tbody>
                {% for commentaire in rencontre.commentaires %}
                    {% set difference = rencontre.heureDebut.diff(commentaire.dateHeure) %}
                    <tr>
                        <td><i>{{ difference.i }}m</i></td>
                        <td>{{ commentaire.texte |e }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
        {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="col-5">
            <h3>Composition équipe {{ rencontre.equipeA.Nom |e }}</h3>
            {% if rencontre.equipeA.joueurs is empty %}
            <p id="msgNoPlayersTeamA">Aucun joueur n'est encore inscrit sur la feuille de match</p>
            {% else %}
            <p>{{ rencontre.equipeA.joueurs |length }} joueurs sont inscrits sur la feuille de match :</p>
            <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseEquipeA" aria-expanded="false" aria-controls="collapseExample">
            Voir la liste des joueurs
            </button>
            <div class="collapse" id="collapseEquipeA">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Numéro</th>
                            <th>Nom</th>
                            <th>Prénom</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for joueur in rencontre.equipeA.joueurs %}
                        <tr>
                            <td>{{ joueur.numero |e }}</td>
                            <td>{{ joueur.nom |e }}</td>
                            <td>{{ joueur.prenom |e }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% endif %}
        </div>
        <div class="col-2"></div>
        <div class="col-5">
            <h3>Composition équipe {{ rencontre.equipeB.Nom |e }}</h3>
            {% if rencontre.equipeB.joueurs is empty %}
            <p id="msgNoPlayersTeamA">Aucun joueur n'est encore inscrit sur la feuille de match</p>
            {% else %}
            <p>{{ rencontre.equipeB.joueurs |length }} joueurs sont inscrits sur la feuille de match :</p>
            <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseEquipeB" aria-expanded="false" aria-controls="collapseExample">
            Voir la liste des joueurs
            </button>
            <div class="collapse" id="collapseEquipeB">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Numéro</th>
                            <th>Nom</th>
                            <th>Prénom</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for joueur in rencontre.equipeB.joueurs %}
                        <tr>
                            <td>{{ joueur.numero |e }}</td>
                            <td>{{ joueur.nom |e }}</td>
                            <td>{{ joueur.prenom |e }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% endif %}
    
        </div>
    </div>
</div>
{% endblock %}